services:
  redis:
    build:
      context: ./C:\Users\Mural\Documents\workspace-spring-tool-suite-4-4.19.0.RELEASE\SpringBootRedis\target
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  SpringBootRedis:
    build:
      context: ./C:\Users\Mural\Documents\workspace-spring-tool-suite-4-4.19.0.RELEASE\SpringBootRedis\target
    ports:
      - "8085:8089"
    depends_on:
      - redis
    


